<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Fresh Produce Co.',
                'contact_person' => 'John Martinez',
                'email' => 'john@freshproduce.com',
                'phone' => '+1-555-0101',
                'address' => '1234 Market Street',
                'city' => 'Los Angeles',
                'state' => 'California',
                'country' => 'US',
                'postal_code' => '90210',
                'tax_id' => 'TAX123456789',
                'website' => 'https://freshproduce.com',
                'status' => 'active',
                'credit_limit' => 50000.00,
                'payment_terms' => 30,
                'notes' => 'Reliable supplier for fresh vegetables and fruits. Delivers daily.',
            ],
            [
                'name' => 'Premium Meats Ltd.',
                'contact_person' => 'Sarah Johnson',
                'email' => 'sarah@premiummeats.com',
                'phone' => '+1-555-0102',
                'address' => '567 Industrial Blvd',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'country' => 'US',
                'postal_code' => '60611',
                'tax_id' => 'TAX987654321',
                'website' => 'https://premiummeats.com',
                'status' => 'active',
                'credit_limit' => 75000.00,
                'payment_terms' => 15,
                'notes' => 'High-quality meat products. USDA certified. Weekly deliveries.',
            ],
            [
                'name' => 'Ocean Fresh Seafood',
                'contact_person' => 'Michael Chen',
                'email' => 'michael@oceanfresh.com',
                'phone' => '+1-555-0103',
                'address' => '890 Harbor Way',
                'city' => 'Seattle',
                'state' => 'Washington',
                'country' => 'US',
                'postal_code' => '98101',
                'tax_id' => 'TAX456789123',
                'website' => 'https://oceanfresh.com',
                'status' => 'active',
                'credit_limit' => 40000.00,
                'payment_terms' => 7,
                'notes' => 'Fresh seafood daily. Sustainable fishing practices.',
            ],
            [
                'name' => 'Dairy Farms United',
                'contact_person' => 'Emily Rodriguez',
                'email' => 'emily@dairyfarms.com',
                'phone' => '+1-555-0104',
                'address' => '123 Farm Road',
                'city' => 'Madison',
                'state' => 'Wisconsin',
                'country' => 'US',
                'postal_code' => '53703',
                'tax_id' => 'TAX789123456',
                'website' => 'https://dairyfarms.com',
                'status' => 'active',
                'credit_limit' => 30000.00,
                'payment_terms' => 21,
                'notes' => 'Organic dairy products. Local Wisconsin farms.',
            ],
            [
                'name' => 'Beverage Distributors Inc.',
                'contact_person' => 'David Wilson',
                'email' => 'david@beveragedist.com',
                'phone' => '+1-555-0105',
                'address' => '456 Distribution Center Dr',
                'city' => 'Atlanta',
                'state' => 'Georgia',
                'country' => 'US',
                'postal_code' => '30309',
                'tax_id' => 'TAX321654987',
                'website' => 'https://beveragedist.com',
                'status' => 'active',
                'credit_limit' => 60000.00,
                'payment_terms' => 30,
                'notes' => 'Full line of beverages. Soft drinks, juices, and specialty drinks.',
            ],
            [
                'name' => 'Specialty Spices & Herbs',
                'contact_person' => 'Maria Garcia',
                'email' => 'maria@specialtyspices.com',
                'phone' => '+1-555-0106',
                'address' => '789 Spice Market Lane',
                'city' => 'San Francisco',
                'state' => 'California',
                'country' => 'US',
                'postal_code' => '94102',
                'tax_id' => 'TAX654987321',
                'website' => 'https://specialtyspices.com',
                'status' => 'active',
                'credit_limit' => 15000.00,
                'payment_terms' => 14,
                'notes' => 'Imported and domestic spices. Organic certified options available.',
            ],
            [
                'name' => 'Kitchen Supplies Pro',
                'contact_person' => 'Robert Taylor',
                'email' => 'robert@kitchensupplies.com',
                'phone' => '+1-555-0107',
                'address' => '321 Commercial Ave',
                'city' => 'Denver',
                'state' => 'Colorado',
                'country' => 'US',
                'postal_code' => '80202',
                'tax_id' => 'TAX147258369',
                'website' => 'https://kitchensupplies.com',
                'status' => 'active',
                'credit_limit' => 25000.00,
                'payment_terms' => 45,
                'notes' => 'Restaurant equipment and supplies. Maintenance services available.',
            ],
            [
                'name' => 'Bakery Ingredients Plus',
                'contact_person' => 'Lisa Anderson',
                'email' => 'lisa@bakeryingredients.com',
                'phone' => '+1-555-0108',
                'address' => '654 Baker Street',
                'city' => 'Portland',
                'state' => 'Oregon',
                'country' => 'US',
                'postal_code' => '97205',
                'tax_id' => 'TAX852741963',
                'website' => 'https://bakeryingredients.com',
                'status' => 'active',
                'credit_limit' => 20000.00,
                'payment_terms' => 30,
                'notes' => 'Professional baking ingredients. Flour, yeast, and specialty items.',
            ],
            [
                'name' => 'Local Organic Farms',
                'contact_person' => 'James Thompson',
                'email' => 'james@localorganic.com',
                'phone' => '+1-555-0109',
                'address' => '987 Farm Gate Road',
                'city' => 'Austin',
                'state' => 'Texas',
                'country' => 'US',
                'postal_code' => '78701',
                'tax_id' => 'TAX963852741',
                'website' => 'https://localorganic.com',
                'status' => 'active',
                'credit_limit' => 35000.00,
                'payment_terms' => 14,
                'notes' => 'Certified organic produce. Seasonal availability. Farm-to-table focus.',
            ],
            [
                'name' => 'International Food Imports',
                'contact_person' => 'Anna Kowalski',
                'email' => 'anna@intlfoodimports.com',
                'phone' => '+1-555-0110',
                'address' => '159 Import Plaza',
                'city' => 'Miami',
                'state' => 'Florida',
                'country' => 'US',
                'postal_code' => '33101',
                'tax_id' => 'TAX741852963',
                'website' => 'https://intlfoodimports.com',
                'status' => 'active',
                'credit_limit' => 45000.00,
                'payment_terms' => 30,
                'notes' => 'Specialty international ingredients. European and Asian products.',
            ],
        ];

        foreach ($suppliers as $supplierData) {
            Supplier::create($supplierData);
        }
    }
}
